<H1> NUMPY</H1>

In [ ]:
#!pip install numpy  numpy in c:\users\91756\anaconda3\lib\site-packages (1.24.3)

In [1]:
import numpy as np

In [ ]:
a1 = np.arange(2,21,2)  #arange is used to create an array(range,step)
a1

In [ ]:
l1 = [2,3,4,5,6,7]
l1*2

In [ ]:
a2 = np.arange(2,42,2) 
a2*2

In [ ]:
type(a2)

In [ ]:
a2.shape

In [ ]:
a2_reshaped=a2.reshape(4,5) #to change order of an array

In [ ]:
a2_reshaped.shape

In [ ]:
a2_reshaped.dtype

In [ ]:
a3 = np.arange(3.2,15.3,dtype='float')
a3

In [ ]:
a = [2,4,5,6,8] #list
a5 = np.array(a)
print(a)
a5

In [ ]:
marks = np.array([98,44.5,32,87,65],dtype='float')
marks

In [ ]:
a = np.array([0.123456789121212], dtype=np.float16)
print("16bit: ", a[0]) 

a = np.array([0.123456789121212], dtype=np.float32)
print("32bit: ", a[0]) 

b = np.array([0.123456789121212121212], dtype=np.float64)
print("64bit: ", b[0]) 

In [ ]:
b = [[2,4,1],[3,6.3,5],[3,7,9.5]]
a6 = np.array(b)
a6

In [ ]:
dt = np.dtype([('age','int32'),('name','U21')])  #age is of int32 bits size and name is of 5 characters
a7 = np.array([(21.4,'ramkrishna'),(13,'chandana surya')],dtype=dt) 

In [ ]:
a7

### slicing

In [4]:
a8 = np.array([[734,396,563],[567,952,142],[405,910,116]])
a8

array([[734, 396, 563],
       [567, 952, 142],
       [405, 910, 116]])

In [5]:
a8[2][1]

910

In [7]:
a8

array([[734, 396, 563],
       [567, 952, 142],
       [405, 910, 116]])

In [ ]:
a8[0:2,0:1]   #[rows,columns]

In [9]:
a8[1:3,1:3]

array([[952, 142],
       [910, 116]])

In [ ]:
a8[1:,2:]

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros([3,512,512],dtype=int)    #[no of arrays,rows,columns]

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]])

In [15]:
np.zeros([2,2,3])

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [17]:
np.ones([3,2,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [18]:
np.eye(4)    #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.pi #pi value

3.141592653589793

In [20]:
np.e #exponential value

2.718281828459045

In [21]:
import math    #tau value
math.tau

6.283185307179586

In [25]:
np.linspace(2,101)      #it will divide between the range ito 50 equal parts by default

array([  2.        ,   4.02040816,   6.04081633,   8.06122449,
        10.08163265,  12.10204082,  14.12244898,  16.14285714,
        18.16326531,  20.18367347,  22.20408163,  24.2244898 ,
        26.24489796,  28.26530612,  30.28571429,  32.30612245,
        34.32653061,  36.34693878,  38.36734694,  40.3877551 ,
        42.40816327,  44.42857143,  46.44897959,  48.46938776,
        50.48979592,  52.51020408,  54.53061224,  56.55102041,
        58.57142857,  60.59183673,  62.6122449 ,  64.63265306,
        66.65306122,  68.67346939,  70.69387755,  72.71428571,
        74.73469388,  76.75510204,  78.7755102 ,  80.79591837,
        82.81632653,  84.83673469,  86.85714286,  88.87755102,
        90.89795918,  92.91836735,  94.93877551,  96.95918367,
        98.97959184, 101.        ])

In [26]:
np.linspace(2,5,10) #it will divide in 10 parts

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [29]:
a = np.linspace(2,101,10,endpoint = False) #not getting end point i.e 5.
a

array([ 2. , 11.9, 21.8, 31.7, 41.6, 51.5, 61.4, 71.3, 81.2, 91.1])

In [31]:
np.linspace(2,101,50,retstep = True)  #shows the difference of two outputs (all outputs)

(array([  2.        ,   4.02040816,   6.04081633,   8.06122449,
         10.08163265,  12.10204082,  14.12244898,  16.14285714,
         18.16326531,  20.18367347,  22.20408163,  24.2244898 ,
         26.24489796,  28.26530612,  30.28571429,  32.30612245,
         34.32653061,  36.34693878,  38.36734694,  40.3877551 ,
         42.40816327,  44.42857143,  46.44897959,  48.46938776,
         50.48979592,  52.51020408,  54.53061224,  56.55102041,
         58.57142857,  60.59183673,  62.6122449 ,  64.63265306,
         66.65306122,  68.67346939,  70.69387755,  72.71428571,
         74.73469388,  76.75510204,  78.7755102 ,  80.79591837,
         82.81632653,  84.83673469,  86.85714286,  88.87755102,
         90.89795918,  92.91836735,  94.93877551,  96.95918367,
         98.97959184, 101.        ]),
 2.020408163265306)

In [32]:
np.linspace(2,10,10)

array([ 2.        ,  2.88888889,  3.77777778,  4.66666667,  5.55555556,
        6.44444444,  7.33333333,  8.22222222,  9.11111111, 10.        ])

In [33]:
np.logspace(2,10,10)    #to find the log values default base is 10

array([1.00000000e+02, 7.74263683e+02, 5.99484250e+03, 4.64158883e+04,
       3.59381366e+05, 2.78255940e+06, 2.15443469e+07, 1.66810054e+08,
       1.29154967e+09, 1.00000000e+10])

In [34]:
np.logspace(2,10,10,base = 2)   #base 2

array([   4.        ,    7.4069977 ,   13.71590373,   25.39841683,
         47.03150375,   87.09056001,  161.26989439,  298.63143413,
        552.99058631, 1024.        ])

In [35]:
np.log10(2)        #base is 10

0.3010299956639812

In [37]:
np.array([21,277,13,40]) / np.array([1,2,3,4])   #division

array([ 21.        , 138.5       ,   4.33333333,  10.        ])

In [38]:
a8

array([[734, 396, 563],
       [567, 952, 142],
       [405, 910, 116]])

In [40]:
 for i in np.nditer(a8):     #nditer is used for iteratoins 
        print(i*2)

1468
792
1126
1134
1904
284
810
1820
232


In [45]:
a = np.random.rand(2,5)   #randomly generates the array between 0 and 1 of size 2*5
a

array([[0.34690095, 0.09365581, 0.17492742, 0.48452951, 0.26755886],
       [0.72882396, 0.57953681, 0.47915283, 0.13938702, 0.98716618]])

In [48]:
a1 = np.random.randn(2,5)  #randomly generates the array in negatives of size 2*5
a1

array([[ 1.27940424,  0.72538657, -0.93264541, -0.66870795, -0.05299673],
       [-0.32753809,  0.56648173, -0.29433898,  0.71187804, -0.29158397]])

In [59]:
a2 = np.random.randint(1,60,size = (3,3))   #only integers value
a2

array([[57,  7, 54],
       [10, 22, 28],
       [50, 11, 34]])

In [60]:
a3 = np.array([[3,6,7]])
a4 = np.concatenate((a2,a3))
a4

array([[57,  7, 54],
       [10, 22, 28],
       [50, 11, 34],
       [ 3,  6,  7]])

In [61]:
a5 = np.array([[3],[6],[7]])
a6 = np.concatenate((a2,a5),axis = 1)
a6

array([[57,  7, 54,  3],
       [10, 22, 28,  6],
       [50, 11, 34,  7]])

### Broadcasting

In [62]:
a = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
b = np.matrix([[100,100,100],[100,100,100],[100,100,100]])

a

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [63]:
b

matrix([[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]])

In [66]:
np.

matrix([[ 600,  600,  600],
        [1500, 1500, 1500],
        [2400, 2400, 2400]])

In [65]:
a-b

matrix([[-99, -98, -97],
        [-96, -95, -94],
        [-93, -92, -91]])

In [ ]:
c = np.matrix([100,100,100])

In [ ]:
c

In [ ]:
a+c

In [ ]:
b+c

In [ ]:
d = np.matrix([100])

In [ ]:
d

In [ ]:
type(d)

In [ ]:
a+d

In [ ]:
b+d

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 9])

In [ ]:
arr

In [ ]:
arr[arr % 2 == 1]

In [2]:
# Reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])

newarr = arr.reshape(2, 2, 3)

print ("Original array:\n", arr)
print("---------------")
print ("Reshaped array:\n", newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
---------------
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [3]:
# Python program to demonstrate
# indexing in numpy
import numpy as np

# An exemplar array
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

# Slicing array
temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate"
                    "columns(0 and 2):\n", temp)

# Integer array indexing example
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),"
                                    "(3, 0):\n", temp)

# boolean array indexing example
cond = arr > 0 # cond is a boolean array
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)


Array with first 2 rows and alternatecolumns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [4]:
# Python program to demonstrate
# basic operations on single array
import numpy as np

a = np.array([1, 2, 5, 3])

# add 1 to every element
print ("Adding 1 to every element:", a+1)

# subtract 3 from each element
print ("Subtracting 3 from each element:", a-3)

# multiply each element by 10
print ("Multiplying each element by 10:", a*10)

# square each element
print ("Squaring each element:", a**2)

# modify existing array
a *= 2
print ("Doubled each element of original array:", a)

# transpose of array
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])

print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)


Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [5]:
# Python program to demonstrate sorting in numpy
import numpy as np

a = np.array([[1, 4, 2],
                 [3, 4, 6],
              [0, -1, 5]])

# sorted array
print ("Array elements in sorted order:\n",
                    np.sort(a, axis = None))

# sort array row-wise
print ("Row-wise sorted array:\n",
                np.sort(a, axis = 1))

# specify sort algorithm
print ("Column wise sort by applying merge-sort:\n",
            np.sort(a, axis = 0, kind = 'mergesort'))

# Example to show sorting of structured array
# set alias names for dtypes
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]

# Values to be put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7), 
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]
           
# Creating array
arr = np.array(values, dtype = dtypes)
print ("\nArray sorted by names:\n",
            np.sort(arr, order = 'name'))
            
print ("Array sorted by graduation year and then cgpa:\n",
                np.sort(arr, order = ['grad_year', 'cgpa']))


Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]
Row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Column wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]

Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by graduation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


In [6]:
# Python program explaining
# numpy.count() function
 
import numpy as np
 
a=np.array(['geeks', 'for', 'geeks'])
 
# counting a substring
print(np.char.count(a,'geek'))
 
# counting a substring
print(np.char.count(a, 'fo'))


[1 0 1]
[0 1 0]


In [7]:
# Python code to demonstrate working of 
# np.lexsort() 
import numpy as np 

# Numpy array created 
a = np.array([9, 3, 1, 3, 4, 3, 6]) # First column 
b = np.array([4, 6, 9, 2, 1, 8, 7]) # Second column 
print('column a, column b') 
for (i, j) in zip(a, b): 
	print(i, ' ', j) 

ind = np.lexsort((b, a)) # Sort by a then by b 
print('Sorted indices->', ind) 


column a, column b
9   4
3   6
1   9
3   2
4   1
3   8
6   7
Sorted indices-> [2 3 1 5 4 6 0]


In [2]:
# 1D arrya
import numpy as np
arr = np.array([1,2,3,4,5,6,7,])
print(arr)

[1 2 3 4 5 6 7]


In [3]:
#2d array
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)


[[1 2 3]
 [4 5 6]]


In [4]:
# 3d array
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [5]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])


7


In [7]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])


2nd element on 1st row:  2


In [8]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])


5th element on 2nd row:  10


In [9]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])


6


In [10]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))


[False  True  True]


In [11]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))


[[2 3 4]
 [0 1 5]]


In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[1 2 3 4 5]


In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)


[42  2  3  4  5]


In [14]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)


[ True False  True]
bool


In [15]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)


[1 2 3]
int32


In [16]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)


[1 2 3]
int32


In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [19]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)


[1 2 3 4 5 6]
